version: "3.4"

services:

  db:
    build: db
    ports:
      - 1433
    healthcheck:
      test: "exit 0"

  api:
    build: api
    volumes:
      - ./api/bin:/app
    command: /bin/sh -c "/wait && node /app/server.js"
    links:
      - "db:db"
    environment:
      - WAIT_HOSTS=db:1433
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - 81:8000
      - 443:443